### ISSUE TITLE
Address for both XMR and BTC donations are the same

### ISSUE THREAD

**Issue by ghost** [mairishavhoon/noteschad#1]
https://noteschad.netlify.app/donate.html

Addresses for both XMR and BTC donations are same. Addresses for both should be different unless you did it 'ironically'. Remove the XMR/BTC address and add a new one.

**Comment by mairishavhoon** [comment]
Alright karen, updated it. PS can you drop some XMR there?

**Comment by LordRishav** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I would if it had some content there‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

On Sunday, June 13th, 2021 at 7:19 PM, Rishav ***@***.***> wrote:

> Alright karen, updated it. PS can you drop some XMR there?
>
> —
>
> You are receiving this because you authored the thread.
>
> Reply to this email directly, view it on GitHub, or unsubscribe.
-----BEGIN PGP SIGNATURE-----
Version: ProtonMail

wsBzBAEBCAAGBQJgxg16ACEJEPLkbCCxtC2kFiEEGbqwNc2katiu6pbj8uRs
ILG0LaSoRAgArYf/Vca08g9TaZnxyLtdSOKJ+UcldvOwhw+j48JWvgZ9RiWC
9sIDf/uEJk06PYw70SMpEeOT+5x9phlLnT+jf4byrhVSp+Dkgt6iFBQKoRTM
xf6wozinTT6dUwG5KWLc9aTuq91qULQCrWJgZpkrZbWvZBH1isCaPno/m05L
1FTM1yVmCbebWl4uR0PmHl74VXlgfPdP44Nq3KtpHdFFYGWHi44wKtVapsds
Ycxlm/urnLL/qQy0AvtNeWcAhsDVg3+EWGlQQms3wgt1Nm8FWGzM98yek9bt
NbpG1q1gEUv1Fplr2S9f+PYrSbvz7pferR7aYkIger067tx9Wrf51g==
=5xBP
-----END PGP SIGNATURE-----

**Comment by ghost** [comment]
I would if it had some content over there
